Script started on 2026-01-27 20:18:10-08:00
]0;richarqn@crystalcove:~/hw2[richarqn@crystalcove ~/hw2]$ gcc PhotoLab.c -ansi -Wall -o PhotoLab

]0;richarqn@crystalcove:~/hw2[richarqn@crystalcove ~/hw2]$ ./PhotoLab

--------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image horizontally
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice: 1. 
Please input the file name to load: EngHall
EngHall.ppm was read successfully!
--------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image horizontally
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice: 11
EngHall.ppm was read successfully!
Negative operation is done!
negative.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in negative_diff.ppm.
negative.jpg was stored for viewing. 
Negative tested!

EngHall.ppm was read successfully!
Color filter operation is done!
colorfilter.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in colorfilter_diff.ppm.
colorfilter.jpg was stored for viewing. 
Color Filter tested!

EngHall.ppm was read successfully!
Edge detection operation is done!
edge.ppm was saved successfully. 
170 mismatching pixels (0.074%) identified in edge_diff.ppm.
edge.jpg was stored for viewing. 
Edge Detection tested!

EngHall.ppm was read successfully!
VMirror operation is done!
vmirror.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in vmirror_diff.ppm.
vmirror.jpg was stored for viewing. 
VMirror tested!

EngHall.ppm was read successfully!
Add Border operation is done!
border.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in border_diff.ppm.
border.jpg was stored for viewing. 
Border tested!

EngHall.ppm was read successfully!
Black & White operation is done!
bw.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in bw_diff.ppm.
bw.jpg was stored for viewing. 
Black & White tested!

EngHall.ppm was read successfully!
HFlip operation is done!
hflip.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in hflip_diff.ppm.
hflip.jpg was stored for viewing. 
HFlip tested!

EngHall.ppm was read successfully!
Shuffle operation is done!
shuffle.ppm was saved successfully. 
0 mismatching pixels (0.000%) identified in shuffle_diff.ppm.
shuffle.jpg was stored for viewing. 
Shuffle tested!

--------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image horizontally
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice: 12
Exiting the program.
]0;richarqn@crystalcove:~/hw2[richarqn@crystalcove ~/hw2]$ exit

exit

Script done on 2026-01-27 20:18:58-08:00
